---
- name: Install postfix
  dnf:
    name:
      - postfix
      - postfix-ldap
    state: present
  notify: reload postfix
- name: Install postfix configuration files
  copy:
    src: postfix/
    dest: /etc/postfix/
  notify: reload postfix
- name: Install main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: reload postfix
- name: Ensure /etc/scripts exists
  file:
    path: /etc/scripts/
    state: directory
- name: Install root's procmailrc
  template:
    src: root-procmailrc.j2
    dest: /etc/scripts/root-procmailrc
- name: Enable postfix
  service:
    name: postfix
    enabled: yes
    state: started
# TODO: Move blocked users from /etc/aliases into LDAP as scriptsMailboxCommand: /bin/false
