---
- name: Install postfix
  dnf:
    name:
      - postfix
      - postfix-ldap
      - procmail
    state: present
  notify: reload postfix
- name: Delay postfix startup until network is online
  copy:
    dest: /etc/systemd/system/postfix.service.d/scripts-postfix-network-online.conf
    content: |
      [Unit]
      Wants=network-online.target
      After=network-online.target
- name: Install postfix configuration files
  copy:
    src: postfix/
    dest: /etc/postfix/
  notify: reload postfix
- name: Install postfix LDAP configuration
  template:
    src: "postfix/{{ item }}.j2"
    dest: /etc/postfix/{{ item }}
  loop:
    - mailbox-command-maps-ldap.cf
    - virtual-alias-domains-ldap.cf
    - virtual-alias-maps-ldap-reserved.cf
    - virtual-alias-maps-ldap.cf
  notify: reload postfix
- name: Install main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: reload postfix
- name: Ensure /etc/scripts exists
  file:
    path: /etc/scripts/
    state: directory
- name: Install root's procmailrc
  template:
    src: root-procmailrc.j2
    dest: /etc/scripts/root-procmailrc
- name: Install aliases
  copy:
    dest: /etc/aliases
    src: aliases
  notify: newaliases
- name: Enable postfix
  service:
    name: postfix
    enabled: yes
    state: started
# TODO: Move blocked users from /etc/aliases into LDAP as scriptsMailboxCommand: /bin/false
